language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mkoujalgi96/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mkoujalgi96/react-test npm test
after_success:
  - docker build -t mkoujalgi96/multi-client ./client
  - docker build -t mkoujalgi96/multi-nginx ./nginx
  - docker build -t mkoujalgi96/multi-server ./server
  - docker build -t mkoujalgi96/multi-worker ./worker
  #login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password -stdin
  #push images to docker-hub
  - docker push mkoujalgi96/multi-client
  - docker push mkoujalgi96/multi-nginx
  - docker push mkoujalgi96/multi-server
  - docker push mkoujalgi96/multi-worker

